export const mockMyFont = {
  "info": {
    "fontSize": -19107,
    "smooth": true,
    "unicode": true,
    "italic": false,
    "bold": false,
    "fixedHeight": false,
    "charSet": 0,
    "stretchH": 100,
    "aa": 1,
    "padding": {
      "up": 0,
      "right": 0,
      "down": 0,
      "left": 0
    },
    "spacing": {
      "horizontal": 2,
      "vertical": 2
    },
    "outline": 0,
    "face": "NicoClean"
  },
  "common": {
    "lineHeight": 18,
    "base": 13,
    "scaleW": 126,
    "scaleH": 179,
    "pages": 1,
    "packed": true,
    "alphaChnl": 0,
    "redChnl": 0,
    "greenChnl": 0,
    "blueChnl": 0
  },
  "pages": [
    "myFont.png"
  ],
  "chars": [
    {
      "id": 32,
      "char": " ",
      "x": 28,
      "y": 170,
      "width": 0,
      "height": 0,
      "xoffset": 0,
      "yoffset": 14,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 33,
      "char": "!",
      "x": 108,
      "y": 108,
      "width": 5,
      "height": 15,
      "xoffset": 2,
      "yoffset": 0,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 34,
      "char": "\"",
      "x": 79,
      "y": 156,
      "width": 7,
      "height": 8,
      "xoffset": 2,
      "yoffset": 0,
      "xadvance": 7,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 35,
      "char": "#",
      "x": 42,
      "y": 22,
      "width": 16,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 15,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 36,
      "char": "$",
      "x": 36,
      "y": 2,
      "width": 12,
      "height": 17,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 37,
      "char": "%",
      "x": 16,
      "y": 125,
      "width": 16,
      "height": 14,
      "xoffset": 1,
      "yoffset": 1,
      "xadvance": 15,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 38,
      "char": "&",
      "x": 82,
      "y": 40,
      "width": 13,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 39,
      "char": "'",
      "x": 88,
      "y": 156,
      "width": 4,
      "height": 8,
      "xoffset": 2,
      "yoffset": 0,
      "xadvance": 4,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 40,
      "char": "(",
      "x": 50,
      "y": 2,
      "width": 7,
      "height": 17,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 41,
      "char": ")",
      "x": 59,
      "y": 2,
      "width": 7,
      "height": 17,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 42,
      "char": "*",
      "x": 55,
      "y": 156,
      "width": 9,
      "height": 9,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 8,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 43,
      "char": "+",
      "x": 23,
      "y": 156,
      "width": 11,
      "height": 11,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 44,
      "char": ",",
      "x": 94,
      "y": 156,
      "width": 5,
      "height": 7,
      "xoffset": 2,
      "yoffset": 10,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 45,
      "char": "-",
      "x": 2,
      "y": 170,
      "width": 10,
      "height": 5,
      "xoffset": 1,
      "yoffset": 6,
      "xadvance": 9,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 46,
      "char": ".",
      "x": 14,
      "y": 170,
      "width": 5,
      "height": 5,
      "xoffset": 2,
      "yoffset": 10,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 47,
      "char": "/",
      "x": 99,
      "y": 2,
      "width": 10,
      "height": 16,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 8,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 48,
      "char": "0",
      "x": 92,
      "y": 57,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 49,
      "char": "1",
      "x": 99,
      "y": 108,
      "width": 7,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 50,
      "char": "2",
      "x": 30,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 51,
      "char": "3",
      "x": 43,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 52,
      "char": "4",
      "x": 97,
      "y": 40,
      "width": 13,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 53,
      "char": "5",
      "x": 56,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 54,
      "char": "6",
      "x": 69,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 55,
      "char": "7",
      "x": 82,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 9,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 56,
      "char": "8",
      "x": 95,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 57,
      "char": "9",
      "x": 108,
      "y": 91,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 58,
      "char": ":",
      "x": 36,
      "y": 156,
      "width": 5,
      "height": 11,
      "xoffset": 2,
      "yoffset": 3,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 59,
      "char": ";",
      "x": 45,
      "y": 125,
      "width": 5,
      "height": 14,
      "xoffset": 2,
      "yoffset": 3,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 60,
      "char": "<",
      "x": 94,
      "y": 142,
      "width": 10,
      "height": 12,
      "xoffset": 2,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 61,
      "char": "=",
      "x": 43,
      "y": 156,
      "width": 10,
      "height": 9,
      "xoffset": 2,
      "yoffset": 5,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 62,
      "char": ">",
      "x": 106,
      "y": 142,
      "width": 10,
      "height": 12,
      "xoffset": 2,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 63,
      "char": "?",
      "x": 54,
      "y": 108,
      "width": 10,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 9,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 64,
      "char": "@",
      "x": 60,
      "y": 22,
      "width": 16,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 15,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 65,
      "char": "A",
      "x": 2,
      "y": 40,
      "width": 14,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 66,
      "char": "B",
      "x": 106,
      "y": 57,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 67,
      "char": "C",
      "x": 18,
      "y": 40,
      "width": 14,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 13,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 68,
      "char": "D",
      "x": 2,
      "y": 57,
      "width": 13,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 69,
      "char": "E",
      "x": 2,
      "y": 108,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 70,
      "char": "F",
      "x": 15,
      "y": 108,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 71,
      "char": "G",
      "x": 34,
      "y": 40,
      "width": 14,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 13,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 72,
      "char": "H",
      "x": 2,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 73,
      "char": "I",
      "x": 115,
      "y": 108,
      "width": 5,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 4,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 74,
      "char": "J",
      "x": 89,
      "y": 108,
      "width": 8,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 75,
      "char": "K",
      "x": 17,
      "y": 57,
      "width": 13,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 76,
      "char": "L",
      "x": 66,
      "y": 108,
      "width": 10,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 9,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 77,
      "char": "M",
      "x": 78,
      "y": 22,
      "width": 15,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 14,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 78,
      "char": "N",
      "x": 32,
      "y": 57,
      "width": 13,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 79,
      "char": "O",
      "x": 95,
      "y": 22,
      "width": 15,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 14,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 80,
      "char": "P",
      "x": 16,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 81,
      "char": "Q",
      "x": 68,
      "y": 2,
      "width": 15,
      "height": 16,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 14,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 82,
      "char": "R",
      "x": 47,
      "y": 57,
      "width": 13,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 83,
      "char": "S",
      "x": 30,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 84,
      "char": "T",
      "x": 44,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 85,
      "char": "U",
      "x": 58,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 86,
      "char": "V",
      "x": 50,
      "y": 40,
      "width": 14,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 87,
      "char": "W",
      "x": 22,
      "y": 22,
      "width": 18,
      "height": 15,
      "xoffset": -1,
      "yoffset": 0,
      "xadvance": 15,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 88,
      "char": "X",
      "x": 66,
      "y": 40,
      "width": 14,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 12,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 89,
      "char": "Y",
      "x": 62,
      "y": 57,
      "width": 13,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 90,
      "char": "Z",
      "x": 72,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 91,
      "char": "[",
      "x": 2,
      "y": 2,
      "width": 7,
      "height": 18,
      "xoffset": 2,
      "yoffset": 0,
      "xadvance": 7,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 92,
      "char": "\\",
      "x": 111,
      "y": 2,
      "width": 10,
      "height": 16,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 9,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 93,
      "char": "]",
      "x": 11,
      "y": 2,
      "width": 7,
      "height": 18,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 94,
      "char": "^",
      "x": 66,
      "y": 156,
      "width": 11,
      "height": 8,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 95,
      "char": "_",
      "x": 113,
      "y": 156,
      "width": 11,
      "height": 5,
      "xoffset": 1,
      "yoffset": 12,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 96,
      "char": "`",
      "x": 21,
      "y": 170,
      "width": 5,
      "height": 5,
      "xoffset": 3,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 97,
      "char": "a",
      "x": 16,
      "y": 142,
      "width": 11,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 98,
      "char": "b",
      "x": 86,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 99,
      "char": "c",
      "x": 29,
      "y": 142,
      "width": 11,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 100,
      "char": "d",
      "x": 100,
      "y": 74,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 101,
      "char": "e",
      "x": 42,
      "y": 142,
      "width": 11,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 102,
      "char": "f",
      "x": 78,
      "y": 108,
      "width": 9,
      "height": 15,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 7,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 103,
      "char": "g",
      "x": 85,
      "y": 2,
      "width": 12,
      "height": 16,
      "xoffset": 0,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 104,
      "char": "h",
      "x": 28,
      "y": 108,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 105,
      "char": "i",
      "x": 2,
      "y": 125,
      "width": 5,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 4,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 106,
      "char": "j",
      "x": 20,
      "y": 2,
      "width": 7,
      "height": 18,
      "xoffset": -1,
      "yoffset": 0,
      "xadvance": 4,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 107,
      "char": "k",
      "x": 41,
      "y": 108,
      "width": 11,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 108,
      "char": "l",
      "x": 9,
      "y": 125,
      "width": 5,
      "height": 15,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 4,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 109,
      "char": "m",
      "x": 71,
      "y": 125,
      "width": 15,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 14,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 110,
      "char": "n",
      "x": 55,
      "y": 142,
      "width": 11,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 111,
      "char": "o",
      "x": 88,
      "y": 125,
      "width": 12,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 112,
      "char": "p",
      "x": 2,
      "y": 91,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 113,
      "char": "q",
      "x": 16,
      "y": 91,
      "width": 12,
      "height": 15,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 114,
      "char": "r",
      "x": 13,
      "y": 156,
      "width": 8,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 7,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 115,
      "char": "s",
      "x": 2,
      "y": 156,
      "width": 9,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 8,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 116,
      "char": "t",
      "x": 34,
      "y": 125,
      "width": 9,
      "height": 14,
      "xoffset": 0,
      "yoffset": 1,
      "xadvance": 7,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 117,
      "char": "u",
      "x": 68,
      "y": 142,
      "width": 11,
      "height": 12,
      "xoffset": 1,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 118,
      "char": "v",
      "x": 102,
      "y": 125,
      "width": 12,
      "height": 12,
      "xoffset": 0,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 119,
      "char": "w",
      "x": 52,
      "y": 125,
      "width": 17,
      "height": 12,
      "xoffset": 0,
      "yoffset": 3,
      "xadvance": 15,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 120,
      "char": "x",
      "x": 2,
      "y": 142,
      "width": 12,
      "height": 12,
      "xoffset": 0,
      "yoffset": 3,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 121,
      "char": "y",
      "x": 77,
      "y": 57,
      "width": 13,
      "height": 15,
      "xoffset": 0,
      "yoffset": 3,
      "xadvance": 11,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 122,
      "char": "z",
      "x": 81,
      "y": 142,
      "width": 11,
      "height": 12,
      "xoffset": 0,
      "yoffset": 3,
      "xadvance": 9,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 123,
      "char": "{",
      "x": 2,
      "y": 22,
      "width": 8,
      "height": 16,
      "xoffset": 0,
      "yoffset": 0,
      "xadvance": 6,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 124,
      "char": "|",
      "x": 29,
      "y": 2,
      "width": 5,
      "height": 18,
      "xoffset": 2,
      "yoffset": 0,
      "xadvance": 5,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 125,
      "char": "}",
      "x": 12,
      "y": 22,
      "width": 8,
      "height": 16,
      "xoffset": 1,
      "yoffset": 0,
      "xadvance": 7,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 126,
      "char": "~",
      "x": 101,
      "y": 156,
      "width": 10,
      "height": 6,
      "xoffset": 2,
      "yoffset": 10,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    },
    {
      "id": 8230,
      "char": "…",
      "x": 29,
      "y": 170,
      "width": 11,
      "height": 5,
      "xoffset": 1,
      "yoffset": 10,
      "xadvance": 10,
      "page": 1,
      "chnl": 0
    }
  ],
  "kernings": []
};

const base64String = 'iVBORw0KGgoAAAANSUhEUgAAAH4AAACzCAYAAABPVajiAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAADxVJREFUeAHtXUuSJasNze6odZSnzyuw9z+yV2BP7Y1g5wCHSqXP0Ye8twwn4kZ3ZSIQCEghCfh1Xde4DrbD7+tgSxzBb4oP+scYX2f9X79+fSNA0vC0Vj4WPU2LpEPyjpRL03Nk6W+6LA8d9ZkwR/znH3+5PFTTaO/uCs0f/dsDTWOVG82rix7lT0KmHTV8SA//9Oe/qgR3z7oL+dc//nZ5mGmj8Boc6d1aHeiIu3n79z//rpaj5TXrbvGi0SPtpuVj4c43Muo/tBdag3jvKLLTEMXdaHel6L+awHgjoXxa+Uyh0bxo5/E6IqentBFUOzLHI8pdZtRP0BEyG9irnDVj0Xy80ScJnedxw6tftgNG84nMJm+p1UsjaFYKbUQ03VNCy2COZLQj30AH2dsu5zQNNjNNvhJ8FGb57+6Ab72Ov4Uv9fZXCD/a6WjH5SsUtLwM0On+LQVPG2n2dN4BKnoDCqkRqVLnQeq43rTNgaaPTvcf1xsjarjpgqS182cTnmDujhtd1lZXJ8jS7i0FLzUyHX1eY3sVR0erN7otrZ+XNfmJTOHR2SGytPtRyt2NriUWzSvKw8TdwSI2DWSm6LJFeN/6t57qqZWQNhTSGNqojzasNE3TRvVGlmSwQWaK6GiXyrN4EwU/K4Y0nIROrZsyjggcrXikYXke0W+2lF7ji6bNjnaEP3PER0yAGrI9l6KjoaV3lbpFaSPpO9bs7kx2sQgcpGdG02hMdAjgIIdvgj/YAycCZ1McwW+KI/hNoWr1HXFedFnH00rmWCs9mn80D05TLT+TRkob5SWK3x4Dlbg1z5Km5T2jbCKI5D9BrWl3mfPH32XLj6SpxvdFYa7ju8N9Jqj9XevNkTypsPgzjwfJIkgthqijSKoLKrBqfF8Grsl29Ro72nGkxpTs0pb10aO/aShPKI9UOBWhZ+P7InhMufOcBiumsxvS9CqNdvo312HQ2LxJG5l5eLoO5xOCb4KPCsBrFM40b3ROj3jMaBr+bdaeefzPtJNf3sBeg0sjMWquftKCqe6kQQTQNQWhDgzt/f13hzuz2vC0TRAP3CvxZcRT4Xm+Zt5JkClIG11onJgUuzYVMF4OOnNpPETy4Pm9u9BvfJvqs8EMK71VWVgeuhtcAdSWcJkpOxMupeHx5RwKJJgBYR75vNDtW5KeEBXS1Ni9gItVHdX7ZGYURQSPR+Bw5nmniO4WkdJHAjboqJ90qxrb44WXTdH9+TAFj4YvRdG5p60iJG6ooYiGelVhzYordIYPj4mu8CVpKkXeWemkKTqja2jlZ+LxVqXr7nxmIIYVIXOiZ342TgTOpjj++E1xBL8pjuA3hbmcy0SzSLQUlagYj97jd/V7KR2S3gL3FHYBHvGV3Z7ouyo9am7WfAt8T7tWruWb0OwK1UOgutyxE27M3QR6qlI1mqRKj8LawmTZMFBjCnVETQthhOcV9vlvZUi/if9W/sv/tfSUZqaV0nvvKvQ8DytvtB5P0kp5RGnR3xLlDokmQXaKZui96R6xNmpT/mpajpV+AnGqHyyYIDNdVc/Jo2lGo7LE89bAbecVe3mElrf9KrgjnjPbrWRkEQn8GE3fy4jgJNoxBqS4PhHIYQp+eq26Gi6LGdVSPQgoMoqGoNxGaKxjTK0A0JmeewyzEUEWXMWC4wIVGy1NlR5RdioKEqdB+OK8zbIkHjzF1kKXkgdvqECO/0CjSYayHItEozwBruPcQGLsqS4k+dm1tpNmAh5t1AVV8NnDd9FoErTzaPQRPlAaqUzOo6XgIrxbiEYXV/DlG4/0zBuRWHoORHGp0mvwaKyOYln1tHQ0L20fwatgHoViBWBo77W0FNUDhiNCj0bndNVf2yuQCWBZEfRyAjE2xXHLbooj+E1xBL8pzOvHKDzb+DACBqx31fcdPEtprXdVWildNj1CJwEe8ei6lGuzIxBM4JUR9RN4+SGBG8iG0M/k9WqR5x6idND1Y9kAiIwBJXpChpY/yrPkeRyAswQxaCF1lqyjXhtodY20HXT9mGdKlTCSLs1opAqFxjPaIFK67Pk+Fr3WsSLu7+qaHp7qkWlxIit0if4J0G3TXCgoHQc6w3nn/HrItlW7Vi81Aip0fpZMpdyOzhPtrKjJuwrJXR514rzdRQWZz8qEJOyIDz8y2iW6aJmdaLtitIJ5HWiGoRtVLxfl48YKh85qegsdyjcseFQAkg87OnI5faTcG5VOV8VTo72qyEKCj35LJB/+E8LvKrcK9GgY3jEznxpKF4F5Jw1HZup8lRCeKreiYHF6CquNO3z6sFZf+V5GloIW7ZPlIqgsW7V6VT4VEdoPzozVQF7UjEVbOQplFW0lrZQ+OiiiR7Ag/MEd7zqBGFviuGU3xRH8pjiC3xRiIEY0mKIaINAZkGDRr6hftrwsuvIUR3wmsECD12jdAQkT2Tpkl30r8syWh6DVVh+1IWuWKi+wgC5rVm0x0sqT+HyFU6aKdidN1obM6TLr1ZWOEZ531AXL02c+gZ2fjLdwy0rOlJVCrCJqppVMrJ4ZWfrUVT9/FCFbvQfN6aBBc78+7VTJImKmlbyH3idQo+tA+3JuRoago2IeeiDl8Y5AAjE5aNp5WvaEdyybRlcFFGV7I9vbkAbiR4d3HmvWieh3PZu2g84DFGWLQhvZWl58TSr507Ph1t2oul/fDUu1ehR8ZK+e5qO6CEXGPV0pj2K5cvcUNOVuontkZcujabVPXmS7llcejdBZhZfb6r2AhPYrORaVhyhpkfK0kzW6AAdiVIIhPEQDEhDazvKy9aN0Uh6ZO2+qbf2/fK4TiLEljlt2UxzBb4oj+E2hBmJ0eZO8wAFtbRpN301j0WbKsegk2k6+JPxGM80EVHinYVh5ZowVGW3XotF46A7WiLZ3R/CKe6TpjdXepEgghrScyZaDIrLj1grYkCC1HeqriMiIw3TSRG3nmd0kmVMbpUsMqgcRcGQdMl7AhgbadhFfRda/0eqk4XSSrmClvxGZrqIuUj7y0G8ipct6C72OKZ3BsxJvdTBCxAMm2c+jQkGnxSwNMmtY/oOVneXDyzCTaYYuugEx47/PfhOj316NXoLVRtr+/kpn+VL2/HlAr/3SaCU6TmuVYf28cqR8LRqNH6Q+Up0idc/QonzNn7ice9KbNIIjPYsZvpSlzQIdgVy5Q8DTpbdJ80w7vEkWMkIfgkFogDaGzOcr8x0diRVBtZzooDGVuycPDZLWuhFL142IQujRdHxHo1eoRMqpzpRvbav/dC7+pfCOH43SaHQeTWa0R8vp+DyGTsTIYEUARyZwIxvsEf3kddYJDQxJHU9zXScQY0cct+ymOILfFEfwmwK+muSG55KN0kTMnhkaSufxVCmD0iL0I3D6RrT90DqERnx3oEN3fhwjGbBQPfUDpUfSrTrZA9406eGd95Nlrv+olpPFXKqt3EVzo9Ufn903N5GdxjW6bKBHtPyJrHuYYwWvHC9V7iq3Sgwnnm+COmci+VfQbQRbgdCJGFZPjtraJzK+bslk6SFD44FPy+/8ueNYqtx56TVXpEVHO1jGTt3t+pVurXpiqq7i5crdE1eAjGBs3g54uXJXQebqkf8HoXc4097uFioPXCdAlmUrvI5RVIxDEqoduE25exI09hwZ9dFGzyqqCDpWFh2daLnl7gmgjVnhv1r3SnychgpP5UCMTppo0AZ9Zk35KI/dgSFeumxAR0dwywnE2BTHLbspjuA3xRH8pmi5moS+R9J0LL8yvEaf83dSHTMBGBTddUTRcjUJNYnev5E4HQMtK5JmACdaoHzxvO6/pWcoPUJjlT2RXdJ9Efzde6rry7lE0RrX2x0y2PZnrWEsXiWHD8+XA6n37NjWM2tg0PSUxqqjlW9VVt92X9JnV2BnqbRrkz+L7v7UyvR+Fh/Sc28XMOXde4bkgbQr51tqz2i7zF94qpeAWKXQPe+UVhphUZ6Q82cqx6hEbeaZ+2cnqFyqo73NSSNZpUbCHSr5t6vgfNydgXeIn+C16+S51TtnHUrUcY5MB14p4OxJI3xF0WHnX+KWHUoQ4mR4jPqVIwNYzvAGk/BEuJS1FTrLQ7UDL7mMaEKqkKT1V4DmQ3nhneWJWSC7VXsVWkf8cPZtR2PFrXBlZDTPdFKIdcVjhz5D8uJ8RWkrCC3ZkOWYtWzR3l9X7PCgjiXNzr/WEa+NLv5Oem/llXl/YOObP14TnPfu4GfhBGJsiuOW3RRH8JviCH5TqCdiaKZFJBDDS2vRddMMJ5DCo0Ge03caUEslUkaHyfubP35C8/96/mbkufV+BY2UBqHRlourTvIYyaCQDL6t4/kOlYiHLXLyhGbancEX3qjKbK/O0KCQ7AqopXKADhi6Lbs6+j9Qhm4gGxaiZlmtQ33+gV2BQjtnN00UkneSls0xlLNrvatIJKdPtAOIgs+4AStntkRt6NmynjI8eT4LCZn7fPinIVI/UfCSWxVRhm5I/vco0EZ6R2SEfiO65bv6nYdt9UiPyghdC07wjl2J0lQRVSAj16tEdY7obKzmc126V4ziunxPmoQMHRJ8iNBo7xCaTDkatDaYP6StOQ+Il1P7fVnODaEnIaFCUi/1Qo41Ok7bQROFV58MPL1lKm1IejqbZPUWc5s0vczO2478ZHBChCazJVt737E92QNaRlVRPd65TXFs9ZviCH5THMFvim/r+AF6vobg9erY/uylG8Z6OuNxq6YfZO09DB9DZes5X1lF20Uq47dH7GU4QI8SRXc6K/1gO3D53xJ4+ki5GY+e5/GcPA/iX4iC05hHmqKHCHabUJ9YNkVs252OHApub+eQvJ3W1vBou4iWoYtYlKJbf69Gi1bHj+MTuBz5k13wa+VNt0prbaU9n218KdY8/nfjPgK7kbzGjGyMkBCtiIVIei+ttK++W/CW0Ff/vmn1fI/6KHqBZn7SvvfuT4Rn5vTMyBKv9JlGI/1fS8Pxqj0KXyx3g2mRg0TfcAatdxpQmuFou5/OjRRaer5hc+eNIZA//lXQlKrqKRRnJ5DgpBlKOFAHKjtUD3ohOml4o2sj5EyZPxfHO7cpjq1+UxzBb4oj+E0B3yYd9S55a/GhePc8uoMewCM+6l1C3vH3iJfroAelO2kqXjT6Xvv/wTqc5dymOMrdpjiC3xRH8JviCH5T/Af7g3h8/HduWgAAAABJRU5ErkJggg==';
// @ts-ignore
export const mockMyFontBMP = Uint8Array.fromBase64(base64String);
