name: CD

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: npm install, build, and deploy
      run: |
        npm install
        npm run build
        git clone https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/Pictogrammers/pictogrammers.github.io
        cp -rf dist/. pictogrammers.github.io/@pictogrammers/components
        cd pictogrammers.github.io
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        sed -i 's/"dist\//"/g' @pictogrammers/components/index.html
        git add .
        git commit -m "Deploy @pictogrammers/components"
        git push
